// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/postgres_storage.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/postgres_storage.go -destination=internal/repository/mocks/postgres_storage_mock.go -package=mocks PostgresStorage
//

// Package mocks is a generated GoMock package.
package mocks
